name: Greet first-time contributors

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello and welcome, thanks for your first issue!'' first issue'
        pr-message: 'Hello and welcome, thanks for your first pull request in my repo!'' first pr'
